language: python
python:
  - 3.5
  - 3.6

services:
  - mysql

install: 
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;' -u root
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test
